export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "Create a surreal underwater world with bioluminescent creatures.",
  "Generate a futuristic cityscape at sunset with flying cars.",
  "Design a whimsical forest inhabited by mythical creatures.",
  "Produce a cyberpunk street scene with neon signs and rain.",
  "Craft an alien landscape with towering, crystalline structures.",
  "Make a vintage-style poster for a fictional space adventure movie.",
  "Generate a tranquil beach scene with a colorful sunset.",
  "Create a steampunk-inspired flying machine in a Victorian setting.",
  "Design a post-apocalyptic wasteland with overgrown ruins.",
  "Produce a fantasy castle atop a floating island in the sky.",
  "Generate an abstract art piece with vibrant colors and geometric shapes.",
  "Design a cozy cabin in a snow-covered forest during winter.",
  "Create an underwater city inhabited by mermaids and sea creatures.",
  "Produce a sci-fi spaceship traveling through a cosmic wormhole.",
  "Craft a scene from a fairy tale with enchanted forests and magical creatures.",
  "Generate a bustling Asian night market with street food stalls.",
  "Design a haunted house with eerie mist and ghostly apparitions.",
  "Create a minimalist art piece inspired by the concept of time.",
  "Produce a lush, tropical jungle with hidden waterfalls.",
  "Craft a scene from a medieval fantasy world with knights and dragons.",
  "A mesmerizing cosmic nebula filled with swirling colors.",
  "A serene lakeside cabin surrounded by autumn foliage.",
  "A bustling futuristic cityscape with holographic billboards.",
  "A whimsical underwater garden with talking sea creatures.",
  "A tranquil Japanese cherry blossom garden in full bloom.",
  "A steampunk airship soaring above a Victorian metropolis.",
  "A secret elven village hidden deep within an ancient forest.",
  "A post-apocalyptic wasteland reclaimed by nature.",
  "A mythical creature's lair in the heart of a volcanic island.",
  "A mesmerizing abstract artwork inspired by fractals.",
  "A charming medieval village nestled in rolling hills.",
  "A cyberpunk hacker's den with neon-lit computer screens.",
  "A haunted mansion with eerie shadows and creaky floors.",
  "A retro-futuristic space station orbiting a distant planet.",
  "A surreal dreamscape with floating islands and surreal creatures.",
  "A vibrant Indian marketplace with spices and textiles.",
  "A majestic dragon guarding a treasure hoard in a cave.",
  "A minimalist art piece exploring the concept of infinity.",
  "A tropical paradise beach with crystal-clear turquoise waters.",
  "A time-traveling adventure with a vintage sci-fi vibe.",
  "An ancient Egyptian pyramid at sunset, surrounded by desert sands.",
  "An ethereal underwater palace inhabited by mermaids and seahorses.",
  "A futuristic space colony on a distant, lush alien planet.",
  "A mystical forest with bioluminescent mushrooms and fireflies.",
  "An enchanted library with floating books and magical tomes.",
  "A bustling cyberpunk market street with futuristic technology.",
  "An abandoned spaceship drifting through the cosmos.",
  "A fantastical circus tent with acrobats and magical performers.",
  "An otherworldly portal leading to a realm of floating islands.",
  "A celestial observatory on a mountaintop under a meteor shower.",
  "An intricate and ornate steampunk time machine.",
  "A haunted pirate ship with ghostly crew members.",
  "A serene Zen garden with raked sand and stone sculptures.",
  "An underwater cityscape with transparent domes and submarines.",
  "A surreal dreamscape with melting clocks and flying fish.",
  "An ancient Mayan temple hidden in a lush rainforest.",
  "A cyberpunk detective's office with holographic evidence boards.",
  "A whimsical fairytale castle in a floating bubble.",
  "An alien market filled with bizarre extraterrestrial goods.",
  "A post-apocalyptic city overrun by nature, with wildlife reclaiming the streets.",
];
